name: Generate snake animation

on:
  schedule: # Ejecutar cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Genera la animación snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg?palette=github-dark

      # Añade el archivo generado y haz un commit
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg
          git commit -m "Update snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
